media:
  input: src/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: site
    label: Site settings
    type: file
    path: src/_data/site.json
    fields:
      - name: title
        type: string
      - name: description
        type: text
      - name: url
        type: string

 

  # === REACT DOCUMENTATION COLLECTION ===

    
  
  # ===Pages ===
  - name: pages
    label: React Docs
    path: docs
    type: collection
    format:  yaml-frontmatter
    filename: "{fields.slug}.md" # This allows files like simple-react-learn.json
    fields:
      - name: title
        label: Document Title
        type: string
        

      - name: slug
        label: URL Slug
        type: string
      

      - name: content
        label: Full Page Content
        type: rich-text # This gives you the entire page area for your docs
  


         


  

          
 
  

   